# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: effd32166386428d13e48c219d6e9fc3b5f82b56504db635ac7275676042c6c4cdaef1ec4c850ed059b2a44e652d7bdefd6933efd557e33628f9029c9c625f83

test:
  secret_key_base: 6eb8c24dcf74c43a2bb8e77123e799a848b7ee038d50a45aed2ebe97a907052f98fca34c65f2807bc909fdda940a5b0e538a1b43090f60c8166f007cd3ce0058

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
